name: Main Workflow Orchestrator

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  # Appelle le scan de sécurité
  security:
    uses: ./.github/workflows/codeql.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  # Appelle le déploiement uniquement si security est OK
  deploy:
    needs: security
    if: github.event_name == 'push'
    uses: ./.github/workflows/static.yml
    permissions:
      contents: read
      pages: write
      id-token: write